server:
  port: 8085
spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
#    active: ms
#    active: sub
#    active: stand
#    active: dispk
    active: yearmonth
# 整合mybtis的配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wyb.shardingjdbc.entity
debug: false

